[2025-03-10T06:41:28.431+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: test_dag.print_date manual__2025-03-10T06:41:27.532792+00:00 [queued]>
[2025-03-10T06:41:28.441+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: test_dag.print_date manual__2025-03-10T06:41:27.532792+00:00 [queued]>
[2025-03-10T06:41:28.442+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-03-10T06:41:28.442+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2025-03-10T06:41:28.442+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-03-10T06:41:28.460+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): print_date> on 2025-03-10 06:41:27.532792+00:00
[2025-03-10T06:41:28.463+0000] {standard_task_runner.py:55} INFO - Started process 62 to run task
[2025-03-10T06:41:28.466+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'test_dag', 'print_date', 'manual__2025-03-10T06:41:27.532792+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/__pycache__/test_dag_ai.py', '--cfg-path', '/tmp/tmpcj7eqfw4']
[2025-03-10T06:41:28.467+0000] {standard_task_runner.py:83} INFO - Job 94: Subtask print_date
[2025-03-10T06:41:28.477+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-10T06:41:28.514+0000] {task_command.py:389} INFO - Running <TaskInstance: test_dag.print_date manual__2025-03-10T06:41:27.532792+00:00 [running]> on host e101f626128c
[2025-03-10T06:41:28.567+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test_dag
AIRFLOW_CTX_TASK_ID=print_date
AIRFLOW_CTX_EXECUTION_DATE=2025-03-10T06:41:27.532792+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-03-10T06:41:27.532792+00:00
[2025-03-10T06:41:28.569+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-03-10T06:41:28.569+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2025-03-10T06:41:28.576+0000] {subprocess.py:86} INFO - Output:
[2025-03-10T06:41:28.604+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-10T06:41:28.614+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-10T06:41:28.617+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=test_dag, task_id=print_date, execution_date=20250310T064127, start_date=20250310T064128, end_date=20250310T064128
[2025-03-10T06:41:28.618+0000] {logging_mixin.py:137} INFO - [2025-03-10T06:41:28.431+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: test_dag.print_date manual__2025-03-10T06:41:27.532792+00:00 [queued]>
[2025-03-10T06:41:28.441+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: test_dag.print_date manual__2025-03-10T06:41:27.532792+00:00 [queued]>
[2025-03-10T06:41:28.442+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-03-10T06:41:28.442+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2025-03-10T06:41:28.442+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-03-10T06:41:28.460+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): print_date> on 2025-03-10 06:41:27.532792+00:00
[2025-03-10T06:41:28.463+0000] {standard_task_runner.py:55} INFO - Started process 62 to run task
[2025-03-10T06:41:28.466+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'test_dag', 'print_date', 'manual__2025-03-10T06:41:27.532792+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/__pycache__/test_dag_ai.py', '--cfg-path', '/tmp/tmpcj7eqfw4']
[2025-03-10T06:41:28.467+0000] {standard_task_runner.py:83} INFO - Job 94: Subtask print_date
[2025-03-10T06:41:28.477+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-10T06:41:28.514+0000] {task_command.py:389} INFO - Running <TaskInstance: test_dag.print_date manual__2025-03-10T06:41:27.532792+00:00 [running]> on host e101f626128c
[2025-03-10T06:41:28.567+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test_dag
AIRFLOW_CTX_TASK_ID=print_date
AIRFLOW_CTX_EXECUTION_DATE=2025-03-10T06:41:27.532792+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-03-10T06:41:27.532792+00:00
[2025-03-10T06:41:28.569+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-03-10T06:41:28.569+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2025-03-10T06:41:28.576+0000] {subprocess.py:86} INFO - Output:
[2025-03-10T06:41:28.604+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-10T06:41:28.614+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/***/.local/lib/python3.7/site-packages/***/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
***.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-10T06:41:28.617+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=test_dag, task_id=print_date, execution_date=20250310T064127, start_date=20250310T064128, end_date=20250310T064128
[2025-03-10T06:41:30.209+0000] {test_dag_ai.py:31} INFO - LLM analysis completed successfully.
[2025-03-10T06:41:30.218+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:120: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2025-03-10T06:41:30.218+0000] {email.py:229} INFO - Email alerting: attempt 1
[2025-03-10T06:41:32.481+0000] {email.py:241} INFO - Sent an alert email to ['monishassan1997@gmail.com']
[2025-03-10T06:41:34.183+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 94 for task print_date (Bash command failed. The command returned a non-zero exit code 1.; 62)
[2025-03-10T06:41:34.231+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-03-10T06:41:34.263+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
