[2025-03-12T08:51:19.425+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: test_dag.print_date scheduled__2025-03-11T08:51:11.874285+00:00 [queued]>
[2025-03-12T08:51:19.437+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: test_dag.print_date scheduled__2025-03-11T08:51:11.874285+00:00 [queued]>
[2025-03-12T08:51:19.437+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-03-12T08:51:19.438+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2025-03-12T08:51:19.438+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-03-12T08:51:19.452+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): print_date> on 2025-03-11 08:51:11.874285+00:00
[2025-03-12T08:51:19.458+0000] {standard_task_runner.py:55} INFO - Started process 56 to run task
[2025-03-12T08:51:19.462+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'test_dag', 'print_date', 'scheduled__2025-03-11T08:51:11.874285+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/__pycache__/test_dag_ai.py', '--cfg-path', '/tmp/tmp64vdmcsn']
[2025-03-12T08:51:19.462+0000] {standard_task_runner.py:83} INFO - Job 99: Subtask print_date
[2025-03-12T08:51:19.478+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-12T08:51:19.501+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:121: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2025-03-12T08:51:19.543+0000] {task_command.py:389} INFO - Running <TaskInstance: test_dag.print_date scheduled__2025-03-11T08:51:11.874285+00:00 [running]> on host d4bb8eff44ae
[2025-03-12T08:51:19.630+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test_dag
AIRFLOW_CTX_TASK_ID=print_date
AIRFLOW_CTX_EXECUTION_DATE=2025-03-11T08:51:11.874285+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-03-11T08:51:11.874285+00:00
[2025-03-12T08:51:19.631+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-03-12T08:51:19.632+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2025-03-12T08:51:19.644+0000] {subprocess.py:86} INFO - Output:
[2025-03-12T08:51:19.680+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-12T08:51:19.692+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-12T08:51:19.697+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=test_dag, task_id=print_date, execution_date=20250311T085111, start_date=20250312T085119, end_date=20250312T085119
[2025-03-12T08:51:19.698+0000] {logging_mixin.py:137} INFO - [2025-03-12T08:51:19.425+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: test_dag.print_date scheduled__2025-03-11T08:51:11.874285+00:00 [queued]>
[2025-03-12T08:51:19.437+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: test_dag.print_date scheduled__2025-03-11T08:51:11.874285+00:00 [queued]>
[2025-03-12T08:51:19.437+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-03-12T08:51:19.438+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2025-03-12T08:51:19.438+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-03-12T08:51:19.452+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): print_date> on 2025-03-11 08:51:11.874285+00:00
[2025-03-12T08:51:19.458+0000] {standard_task_runner.py:55} INFO - Started process 56 to run task
[2025-03-12T08:51:19.462+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'test_dag', 'print_date', 'scheduled__2025-03-11T08:51:11.874285+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/__pycache__/test_dag_ai.py', '--cfg-path', '/tmp/tmp64vdmcsn']
[2025-03-12T08:51:19.462+0000] {standard_task_runner.py:83} INFO - Job 99: Subtask print_date
[2025-03-12T08:51:19.478+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-12T08:51:19.501+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:121: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2025-03-12T08:51:19.543+0000] {task_command.py:389} INFO - Running <TaskInstance: test_dag.print_date scheduled__2025-03-11T08:51:11.874285+00:00 [running]> on host d4bb8eff44ae
[2025-03-12T08:51:19.630+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test_dag
AIRFLOW_CTX_TASK_ID=print_date
AIRFLOW_CTX_EXECUTION_DATE=2025-03-11T08:51:11.874285+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-03-11T08:51:11.874285+00:00
[2025-03-12T08:51:19.631+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-03-12T08:51:19.632+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2025-03-12T08:51:19.644+0000] {subprocess.py:86} INFO - Output:
[2025-03-12T08:51:19.680+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-12T08:51:19.692+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/***/.local/lib/python3.7/site-packages/***/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
***.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-12T08:51:19.697+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=test_dag, task_id=print_date, execution_date=20250311T085111, start_date=20250312T085119, end_date=20250312T085119
[2025-03-12T08:51:21.454+0000] {test_dag_ai.py:31} INFO - LLM analysis completed successfully.
[2025-03-12T08:51:21.470+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:120: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2025-03-12T08:51:21.471+0000] {email.py:229} INFO - Email alerting: attempt 1
[2025-03-12T08:51:23.383+0000] {email.py:241} INFO - Sent an alert email to ['anubhav69@gmail.com']
[2025-03-12T08:51:25.004+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 99 for task print_date (Bash command failed. The command returned a non-zero exit code 1.; 56)
[2025-03-12T08:51:25.061+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-03-12T08:51:25.102+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
