[2025-03-08T19:49:22.365+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: test_dag.print_date manual__2025-03-08T19:35:53.506228+00:00 [queued]>
[2025-03-08T19:49:22.378+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: test_dag.print_date manual__2025-03-08T19:35:53.506228+00:00 [queued]>
[2025-03-08T19:49:22.378+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-03-08T19:49:22.378+0000] {taskinstance.py:1284} INFO - Starting attempt 4 of 5
[2025-03-08T19:49:22.378+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-03-08T19:49:22.393+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): print_date> on 2025-03-08 19:35:53.506228+00:00
[2025-03-08T19:49:22.397+0000] {standard_task_runner.py:55} INFO - Started process 98 to run task
[2025-03-08T19:49:22.400+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'test_dag', 'print_date', 'manual__2025-03-08T19:35:53.506228+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/__pycache__/test_dag_ai.py', '--cfg-path', '/tmp/tmppht1mqpj']
[2025-03-08T19:49:22.401+0000] {standard_task_runner.py:83} INFO - Job 51: Subtask print_date
[2025-03-08T19:49:22.411+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-08T19:49:22.450+0000] {task_command.py:389} INFO - Running <TaskInstance: test_dag.print_date manual__2025-03-08T19:35:53.506228+00:00 [running]> on host 1d5c1ffaa84f
[2025-03-08T19:49:22.502+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test_dag
AIRFLOW_CTX_TASK_ID=print_date
AIRFLOW_CTX_EXECUTION_DATE=2025-03-08T19:35:53.506228+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-03-08T19:35:53.506228+00:00
[2025-03-08T19:49:22.504+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-03-08T19:49:22.504+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'date']
[2025-03-08T19:49:22.513+0000] {subprocess.py:86} INFO - Output:
[2025-03-08T19:49:22.560+0000] {subprocess.py:93} INFO - Sat Mar  8 19:49:22 UTC 2025
[2025-03-08T19:49:22.561+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-08T19:49:22.580+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=test_dag, task_id=print_date, execution_date=20250308T193553, start_date=20250308T194922, end_date=20250308T194922
[2025-03-08T19:49:22.581+0000] {test_dag_ai.py:60} ERROR - Error reading log file: [Errno 2] No such file or directory: '/opt/***/logs/dag_id=test_dag/run_id=manual__2025-03-08T19_35_53_506228+00_00/task_id=print_date/attempt=4.log'
[2025-03-08T19:49:22.586+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:120: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2025-03-08T19:49:22.586+0000] {email.py:229} INFO - Email alerting: attempt 1
[2025-03-08T19:49:24.217+0000] {email.py:241} INFO - Sent an alert email to ['monishassan1997@gmail.com']
[2025-03-08T19:49:25.841+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-03-08T19:49:25.879+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
