[2025-03-11T05:54:36.881+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: test_dag.print_date manual__2025-03-11T05:54:34.774177+00:00 [queued]>
[2025-03-11T05:54:36.890+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: test_dag.print_date manual__2025-03-11T05:54:34.774177+00:00 [queued]>
[2025-03-11T05:54:36.890+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-03-11T05:54:36.890+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2025-03-11T05:54:36.891+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-03-11T05:54:36.900+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): print_date> on 2025-03-11 05:54:34.774177+00:00
[2025-03-11T05:54:36.904+0000] {standard_task_runner.py:55} INFO - Started process 56 to run task
[2025-03-11T05:54:36.909+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'test_dag', 'print_date', 'manual__2025-03-11T05:54:34.774177+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/__pycache__/test_dag_ai.py', '--cfg-path', '/tmp/tmpln7esd28']
[2025-03-11T05:54:36.910+0000] {standard_task_runner.py:83} INFO - Job 97: Subtask print_date
[2025-03-11T05:54:36.920+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-11T05:54:36.963+0000] {task_command.py:389} INFO - Running <TaskInstance: test_dag.print_date manual__2025-03-11T05:54:34.774177+00:00 [running]> on host 66ab9e4cb3bf
[2025-03-11T05:54:37.030+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test_dag
AIRFLOW_CTX_TASK_ID=print_date
AIRFLOW_CTX_EXECUTION_DATE=2025-03-11T05:54:34.774177+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-03-11T05:54:34.774177+00:00
[2025-03-11T05:54:37.031+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-03-11T05:54:37.032+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2025-03-11T05:54:37.040+0000] {subprocess.py:86} INFO - Output:
[2025-03-11T05:54:37.065+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-11T05:54:37.075+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-11T05:54:37.079+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=test_dag, task_id=print_date, execution_date=20250311T055434, start_date=20250311T055436, end_date=20250311T055437
[2025-03-11T05:54:37.080+0000] {logging_mixin.py:137} INFO - [2025-03-11T05:54:36.881+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: test_dag.print_date manual__2025-03-11T05:54:34.774177+00:00 [queued]>
[2025-03-11T05:54:36.890+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: test_dag.print_date manual__2025-03-11T05:54:34.774177+00:00 [queued]>
[2025-03-11T05:54:36.890+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-03-11T05:54:36.890+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2025-03-11T05:54:36.891+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-03-11T05:54:36.900+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): print_date> on 2025-03-11 05:54:34.774177+00:00
[2025-03-11T05:54:36.904+0000] {standard_task_runner.py:55} INFO - Started process 56 to run task
[2025-03-11T05:54:36.909+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'test_dag', 'print_date', 'manual__2025-03-11T05:54:34.774177+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/__pycache__/test_dag_ai.py', '--cfg-path', '/tmp/tmpln7esd28']
[2025-03-11T05:54:36.910+0000] {standard_task_runner.py:83} INFO - Job 97: Subtask print_date
[2025-03-11T05:54:36.920+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-11T05:54:36.963+0000] {task_command.py:389} INFO - Running <TaskInstance: test_dag.print_date manual__2025-03-11T05:54:34.774177+00:00 [running]> on host 66ab9e4cb3bf
[2025-03-11T05:54:37.030+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test_dag
AIRFLOW_CTX_TASK_ID=print_date
AIRFLOW_CTX_EXECUTION_DATE=2025-03-11T05:54:34.774177+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-03-11T05:54:34.774177+00:00
[2025-03-11T05:54:37.031+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-03-11T05:54:37.032+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2025-03-11T05:54:37.040+0000] {subprocess.py:86} INFO - Output:
[2025-03-11T05:54:37.065+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-11T05:54:37.075+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/***/.local/lib/python3.7/site-packages/***/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
***.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-11T05:54:37.079+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=test_dag, task_id=print_date, execution_date=20250311T055434, start_date=20250311T055436, end_date=20250311T055437
[2025-03-11T05:54:38.930+0000] {test_dag_ai.py:31} INFO - LLM analysis completed successfully.
[2025-03-11T05:54:38.939+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:120: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2025-03-11T05:54:38.939+0000] {email.py:229} INFO - Email alerting: attempt 1
[2025-03-11T05:54:41.110+0000] {email.py:241} INFO - Sent an alert email to ['anubhav69@gmail.com']
[2025-03-11T05:54:42.936+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 97 for task print_date (Bash command failed. The command returned a non-zero exit code 1.; 56)
[2025-03-11T05:54:42.973+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-03-11T05:54:43.013+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
